- name: Demo on conditions playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Print OS redhat
      ansible.builtin.debug:
        msg: Redhat
      when: os == "redhat"

    - name: Print OS ubuntu
      ansible.builtin.debug:
        msg: Ubuntu
      when: os == "ubuntu"