- name: Demo on conditions playbook
  hosts: localhost
  connection: local
  vars:
    to_install: true
  tasks:
    - name: Print OS redhat
      ansible.builtin.debug:
        msg: Redhat
      when: os == "redhat"

    - name: Print OS ubuntu
      ansible.builtin.debug:
        msg: Ubuntu
      when: os == "ubuntu"

    - name: Register reminder
      ansible.builtin.shell: echo $(({{number}}%2))
      register: reminder

    - name: Print even number
      ansible.builtin.debug:
        msg: Number {{number}} is even
      when: reminder.stdout == '0'

    - name: Boolean condition
      ansible.builtin.debug:
        msg: to_install is true
      when: to_install